name: Push to GCR GitHub Action tdv2-showcase-web Production

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
env:
  REGISTRY: asia.gcr.io
  REGISTRY_NAME: tdv2-showcase-web
  PROJECT_ID: ascendant-chain-336811
  SHA: ${GITHUB_SHA}

jobs:
  build-and-push-production:
    if: ${{ github.ref_type == 'tag' && github.event.base_ref=='refs/heads/main' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Get the tag name
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - uses: RafikFarhad/push-to-gcr-github-action@v4.1.0
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: ${{ env.REGISTRY }}
          project_id: ${{ env.PROJECT_ID }}
          image_name: ${{ env.REGISTRY_NAME }}
          image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}

      - uses: appleboy/telegram-action@master
        name: send release notif to telegram
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Release!!!
            ${{ github.actor }} has released ${{ github.repository }} service.
            
            See release: https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_tag_name.outputs.GIT_TAG_NAME }}

            !!!don't forget to update https://github.com/fazpass/fazpass-infra, so that it deploys to the server!!!
